name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    name: ${{ matrix.package }}
    strategy: 
      matrix:
        package: [cra, todomvc]
    steps:
      - uses: actions/checkout@v1
      - name: cd, yarn, test
        run: |
          cd ${{ matrix.package }}
          yarn
          yarn test
